config/routes.rb
Rails.application.routes.draw do

  # root
  get "/" => 'frontpage#show'

  resources :uploads



  # backend
  get "/backend" => redirect("/backend/posts"), as: "backend_root"
  namespace :backend do |backend|
    resources :posts
    resources :categories
  end



  # front end

  # posts
  resources :posts, only: [:index, :show]
  get "/:year/:month/:day/:handle" => 'posts#show'

  # categories
  resources :categories, only: [:show], path: "category"

  # tags
  get '/tags/:id' => 'tags#show', as: 'tag'

  # search
  get '/search' => 'search_results#show', as: "search_results"



  devise_for :users

  as :user do
    get "/login" => "devise/sessions#new", as: "user_login"
    get "/signin" => redirect("login")
    delete "/logout" => "devise/sessions#destroy"
  end

  root 'frontpage#show'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                :integer          not null, primary key
#  title             :string(191)
#  body              :text(65535)
#  handle            :string(191)
#  author_id         :integer
#  type              :string(191)
#  featured_image_id :string(191)
#  published_at      :datetime
#  deleted_at        :datetime
#  excerpt           :text(65535)
#  origin_title      :string(191)
#  origin_url        :string(191)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  category_id       :integer
#

class Post < ActiveRecord::Base

  # associations
  has_many :uploads
  belongs_to :category
  has_one :author, :foreign_key => 'id', :class_name => "User"


  # fetured image
  attachment :featured_image


  # tags
  acts_as_taggable


  # validations
  validates :title, presence: true
  # validates :featured_image, presence: true


  # filter
  default_scope { order('published_at DESC, created_at DESC') }
  scope :published, lambda { where(['published_at IS NOT NULL']) }


  # search
  searchable do
    # The :more_like_this option must be set to true
    text :title, :more_like_this => true
    text :handle, :more_like_this => true
    text :body, :more_like_this => true
    time :published_at
  end


  # navigation
  def next
    self.class.published.where("id > ?", id).first
  end
  def previous
    self.class.published.where("id < ?", id).last
  end


  # html to markdown before save
  before_save :convert_to_markdown
  def convert_to_markdown
    self.body = ReverseMarkdown.convert body
    self.excerpt = ReverseMarkdown.convert excerpt
  end


  # generate handle before create
  before_create :generate_handle
  def generate_handle
    self.handle = self.title.parameterize if self.title != ""
  end


  # author
  def author
    User.find(author_id)
  end


  # methods
  def handle_status(params)
    if params[:commit] == "Publish"
      self.update(published_at: DateTime.now)
    end

    if params[:commit] == "Unpublish"
      self.update(published_at: nil)
    end
  end


  # methods
  def published?
    published_at != nil
  end

  def unpublished?
    published_at == nil
  end

  def status
    if published?
      return "Published"
    else
      return "Draft"
    end
  end
end

app/controllers/backend/backend_controller.rb
class Backend::BackendController < ApplicationController
  before_action :authenticate_user!

  layout "backend"
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < Backend::BackendController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to backend_categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to backend_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to backend_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :handle, :description, :active, :position)
    end
end

app/controllers/backend/posts_controller.rb
class Backend::PostsController < Backend::BackendController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to backend_posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.handle_status(params)

        format.html { redirect_to backend_posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to backend_posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :handle, :author_id, :type, :featured_image, :remove_featured_image, :published_at, :deleted_at, :excerpt, :origin_title, :origin_url, :category_id, :tag_list)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.published
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @title = @post.title

    @post_next = @post.next
    @post_previous = @post.previous
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      if params[:id] != nil
        @post = Post.find(params[:id])
      else
        @post = Post.where(handle: params[:handle]).first
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def post_path(post)
    if post.published_at
      return "/#{post.published_at.strftime("%Y")}/#{post.published_at.strftime("%m")}/#{post.published_at.strftime("%d")}/#{post.handle}"
    else
      super
    end
  end

  def share_post_url(post)
    return "#{request.protocol}#{request.host}#{post_path(post)}"
  end
end

app/views/backend/posts/_form.html.erb
<%= simple_form_for(@post, url: url) do |f| %>
  <%= f.error_notification %>

  <%#= f.hidden_field :author_id, value: current_user.id %>

  <div class="row">
    <div class="col-sm-8">
      <div class="form-inputs">
        <%= f.input :title, label: false, placeholder: "Title", input_html: { class: "input-lg" } %>
        <%= f.input :handle, label: false, placeholder: "Handle", input_html: { class: "input-sm" } %>
        <%= f.association :category, collection: Category.all.collect { |l| [l.title, l.id] }, include_blank: false %>
        <%= f.input :excerpt, label: "Teaser", input_html: { value: markdown(@post.excerpt) } %>
        <%= f.input :body, input_html: { value: markdown(@post.body) } %>

        <%#= f.input :origin_title %>
        <%#= f.input :origin_url %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= link_to "Preview", post_path(@post), class: "btn btn-default btn-xs pull-right" if @post.id != nil %>
            Publish
          </h3>
        </div>
        <div class="panel-body">
          <% if @post.published? %>
            <p>
              Published on <b><%= @post.published_at.strftime("%d.%m.%Y, %H:%M") %></b>
            </p>
          <% else %>
            <p>
              Not published.
            </p>
          <% end %>
          <%= f.input :author_id, label: "Author", collection: User.all.collect { |l| [l.firstname, l.id] }, include_blank: false %>
        </div>
        <div class="panel-footer clearfix">
          <% if @post.published? %>
            <%= f.button :submit, "Unpublish", class: "btn-sm pull-left" %>
            <%= f.button :submit, "Update", class: "btn-primary btn-sm pull-right" %>
          <% else %>
            <%= f.button :submit, "Save Draft", class: "btn-sm pull-left" %>
            <%= f.button :submit, "Publish", class: "btn-primary btn-sm pull-right" %>
          <% end %>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            Featured Image
          </h3>
        </div>
        <div class="panel-body">
          <%= image_tag attachment_url(@post, :featured_image, :fill, 1000, 1000, format: 'jpg'), class: "img-responsive" if @post.featured_image_id %><br>
          <%= f.attachment_field :featured_image, direct: true %>
          <%= f.check_box :remove_featured_image %>
          <%= f.label :remove_featured_image %>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            Tags
          </h3>
        </div>
        <div class="panel-body">
          <%= f.input :tag_list, label: false, placeholder: "Add Tags", input_html: { value: @post.tag_list.to_s } %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/backend/posts/edit.html.erb
<div class="page-header">
  <h1>Editing Post</h1>
</div>

<div class="post-editing-mode">
  <%= render 'form', url: backend_post_path(@post) %>
</div>

app/views/backend/posts/index.html.erb
<div class="page-header">
  <%= link_to 'New Post', new_backend_post_path, class: "btn btn-primary pull-right" %>
  <h1>Listing Posts</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><b><%= link_to post.title, edit_backend_post_path(post) %></b></td>
        <td><%= post.author.firstname %></td>
        <td><%= post.status %></td>
        <td><%= link_to 'Preview', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_backend_post_path(post) %></td>
        <td><%= link_to 'Destroy', backend_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/backend/posts/new.html.erb
<div class="page-header">
  <h1>New Post</h1>
</div>

<%= render 'form', url: backend_posts_path %>