config/routes.rb
Rails.application.routes.draw do

  # root
  get "/" => 'frontpage#show'

  resources :uploads



  # backend
  get "/backend" => redirect("/backend/posts"), as: "backend_root"
  namespace :backend do |backend|
    resources :posts
    resources :categories
  end



  # front end

  # posts
  resources :posts, only: [:index, :show]
  get "/:year/:month/:day/:handle" => 'posts#show'

  # categories
  resources :categories, only: [:show], path: "category"

  # tags
  get '/tags/:id' => 'tags#show', as: 'tag'

  # search
  get '/search' => 'search_results#show', as: "search_results"



  devise_for :users

  as :user do
    get "/login" => "devise/sessions#new", as: "user_login"
    get "/signin" => redirect("login")
    delete "/logout" => "devise/sessions#destroy"
  end

  root 'frontpage#show'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                :integer          not null, primary key
#  title             :string(191)
#  body              :text(65535)
#  handle            :string(191)
#  author_id         :integer
#  type              :string(191)
#  featured_image_id :string(191)
#  published_at      :datetime
#  deleted_at        :datetime
#  excerpt           :text(65535)
#  origin_title      :string(191)
#  origin_url        :string(191)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  category_id       :integer
#

class Post < ActiveRecord::Base

  # associations
  has_many :uploads
  belongs_to :category
  has_one :author, :foreign_key => 'id', :class_name => "User"


  # fetured image
  attachment :featured_image


  # tags
  acts_as_taggable


  # validations
  validates :title, presence: true
  # validates :featured_image, presence: true


  # filter
  default_scope { order('published_at DESC, created_at DESC') }
  scope :published, lambda { where(['published_at IS NOT NULL']) }


  # search
  searchable do
    # The :more_like_this option must be set to true
    text :title, :more_like_this => true
    text :handle, :more_like_this => true
    text :body, :more_like_this => true
    time :published_at
  end


  # navigation
  def next
    self.class.published.where("id > ?", id).first
  end
  def previous
    self.class.published.where("id < ?", id).last
  end


  # html to markdown before save
  before_save :convert_to_markdown
  def convert_to_markdown
    self.body = ReverseMarkdown.convert body
    self.excerpt = ReverseMarkdown.convert excerpt
  end


  # generate handle before create
  before_create :generate_handle
  def generate_handle
    self.handle = self.title.parameterize if self.title != ""
  end


  # author
  def author
    User.find(author_id)
  end


  # methods
  def handle_status(params)
    if params[:commit] == "Publish"
      self.update(published_at: DateTime.now)
    end

    if params[:commit] == "Unpublish"
      self.update(published_at: nil)
    end
  end


  # methods
  def published?
    published_at != nil
  end

  def unpublished?
    published_at == nil
  end

  def status
    if published?
      return "Published"
    else
      return "Draft"
    end
  end
end

app/controllers/backend/posts_controller.rb
class Backend::PostsController < Backend::BackendController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to backend_posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.handle_status(params)

        format.html { redirect_to backend_posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to backend_posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :handle, :author_id, :type, :featured_image, :remove_featured_image, :published_at, :deleted_at, :excerpt, :origin_title, :origin_url, :category_id, :tag_list)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.published
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @title = @post.title

    @post_next = @post.next
    @post_previous = @post.previous
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      if params[:id] != nil
        @post = Post.find(params[:id])
      else
        @post = Post.where(handle: params[:handle]).first
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def post_path(post)
    if post.published_at
      return "/#{post.published_at.strftime("%Y")}/#{post.published_at.strftime("%m")}/#{post.published_at.strftime("%d")}/#{post.handle}"
    else
      super
    end
  end

  def share_post_url(post)
    return "#{request.protocol}#{request.host}#{post_path(post)}"
  end
end

app/views/posts/_actions.html.erb
<div class="article-actions">
  <span>
    Share
  </span>

  <span class="pull-right">
    <div class="social-share social-share-facebook">
      <a class="social" href="http://www.facebook.com/sharer.php?u=<%=u share_post_url(@post) %>" target="_blank">
        <i class="fa fa-facebook"></i>
      </a>
    </div>
    ·
    <div class="social-share social-share-twitter">
      <a class="social" href="https://twitter.com/intent/tweet?text=<%=u @post.title %>&url=<%=u share_post_url(@post) %>&via=lovemesomemag" target="_blank">
        <i class="fa fa-twitter"></i>
      </a>
    </div>
    ·
    <div class="social-share social-share-pinterest">
      <a class="social" href="//www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark"  data-pin-color="white" data-pin-height="20"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_white_20.png" /></a>
    </div>
  </span>
</div>

app/views/posts/_excerpt.html.erb
<article id="article-excerpt-<%= post.id %>" class="article-excerpt">
  <div class="article-excerpt-category">
    <%= link_to post.category.title, category_path(post.category) %>
  </div>
  <div class="article-excerpt-headline">
    <h2>
      <a href="<%= url_for post_path(post) %>">
        <%= post.title %>
      </a>
    </h2>
  </div>
  <div class="article-excerpt-image">
    <%= link_to post_path(post) do %>
      <%= image_tag attachment_url(post, :featured_image, :fill, 328, 0, format: 'jpg'), "data-hires" => attachment_url(post, :featured_image, :fill, 656, 0, format: 'jpg'),  nopin: "nopin", alt: post.title, title: post.title %>
    <% end %>
  </div>
  <div class="article-excerpt-body">
    <%= sanitize(markdown(post.excerpt), :tags=>[]) %>
  </div>
  <div class="article-excerpt-meta">
    <span class="article-excerpt-author">
      by Linda
    </span>
    <span class="article-excerpt-publishing-date">
      on <%= post.published_at.strftime("%B %d, %Y") %>
    </span>
  </div>
</article>

app/views/posts/_header.html.erb
<h2 class="article-headline">
  <%= link_to @post.title, @post %>
</h2>
<div class="article-meta">
  in
  <%= link_to @post.category.title, @post.category %>
  on
  <%= post.published_at.strftime("%B %d, %Y") %>
</div>

app/views/posts/_listing.html.erb
<div id="articles-listing-excerpt" class="articles-listing articles-listing-excerpt">
  <% posts.each do |post| %>
    <%= render 'posts/excerpt', post: post %>
  <% end %>
</div>

app/views/posts/_meta.html.erb
<div class="article-author">
  by Linda
</div>

<!-- <?php $origin_title = $post->__get("origin_title"); ?>
<?php $origin_url = $post->__get("origin_url"); ?>
<?php if ($origin_title && $origin_url): ?>
  <div class="article-origin">
    <b>Inspired by:</b> <a href="<?php echo $origin_url; ?>" target="_blank"><?php echo $origin_title; ?></a>
  </div>
<?php endif; ?> -->

<% unless @post.tags.empty? %>
  <div class="article-tags">
    <b>Tags:</b>
    <% for tag in @post.tags %>
      <a href="<%= tag_path("#{tag.id}-#{tag.name.parameterize}") %>"><%= tag.name %></a><% if tag != @post.tags.last %>,<% end %>
    <% end %>
  </div>
<% end %>

app/views/posts/_navigation.html.erb
<div class="article-navigation">
  <div class="article-nav article-nav-prev">
    <a href="<%= post_path(@post_previous) %>">
      <small>previous</small>
      <h3><%= @post_previous.title %></h3>
    </a>
  </div>
  <div class="article-nav article-nav-next">
    <% if @post_next %>
      <a href="<%= post_path(@post_next) %>">
        <small>next</small>
        <h3><%= @post_next.title %></h3>
      </a>
    <% else %>
      <small>this is the</small>
      <h3>most recent post</h3>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% if @posts.count > 0 %>
  <div id="articles-listing-excerpt" class="articles-listing articles-listing-excerpt">
    <% @posts.each do |post| %>
      <%= render 'posts/excerpt', post: post %>
    <% end %>
  </div>
<% else %>
  <p>Apologies, but this category has currently no posts.</p>
<% end %>

app/views/posts/show.html.erb
<article id="article-<%= @post.id %>" class="article article-show">
  <%= render 'posts/header', post: @post %>

  <div class="article-body">
    <div class="article-content">
      <%= markdown(@post.excerpt) %>
      <%= markdown(@post.body) %>
    </div>

    <%= render 'posts/meta', post: @post %>
  </div>

  <%= render 'posts/actions', post: @post %>
</article>

<%#= render 'posts/navigation', post: @post %>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'lovemesomemag';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>