config/routes.rb
Rails.application.routes.draw do

  # root
  get "/" => 'frontpage#show'

  resources :uploads



  # backend
  get "/backend" => redirect("/backend/posts"), as: "backend_root"
  namespace :backend do |backend|
    resources :posts
    resources :categories
  end



  # front end

  # posts
  resources :posts, only: [:index, :show]
  get "/:year/:month/:day/:handle" => 'posts#show'

  # categories
  resources :categories, only: [:show], path: "category"

  # tags
  get '/tags/:id' => 'tags#show', as: 'tag'

  # search
  get '/search' => 'search_results#show', as: "search_results"



  devise_for :users

  as :user do
    get "/login" => "devise/sessions#new", as: "user_login"
    get "/signin" => redirect("login")
    delete "/logout" => "devise/sessions#destroy"
  end

  root 'frontpage#show'
end

app/models/upload.rb
# == Schema Information
#
# Table name: uploads
#
#  id         :integer          not null, primary key
#  image_id   :string(191)
#  post_id    :integer
#  deleted_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Upload < ActiveRecord::Base
  # associations
  belongs_to :post


  # fetured image
  attachment :image
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.json { render :show, status: :created, location: @upload }
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:image, :post_id, :deleted_at)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= simple_form_for(@upload) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.attachment_field :image %>
    <%= f.input :post_id %>
    <%= f.input :deleted_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Post</th>
      <th>Deleted at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td>
          <%= image_tag attachment_url(upload, :image, :fill, 300, 300, format: "jpg") %>
        </td>
        <td><%= upload.post_id %></td>
        <td><%= upload.deleted_at %></td>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @upload.image_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @upload.post_id %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @upload.deleted_at %>
</p>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>